# Generated by Django 4.2.7 on 2023-11-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0003_alter_customer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('dine-in', 'Dine in'), ('take-away', 'Take Away'), ('home-delivery', 'Home Delivery')], default='pending', max_length=20),
        ),
    ]
