# Generated by Django 4.2.7 on 2023-11-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0004_alter_order_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('dine-in', 'Dine in'), ('take-away', 'Take Away'), ('home-delivery', 'Home Delivery')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, default='pending', max_length=50, null=True),
        ),
    ]
