# Generated by Django 4.2.7 on 2023-11-16 08:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=300)),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("opening_time", models.TimeField()),
                ("closing_time", models.TimeField()),
                ("phone_number", models.CharField(max_length=20)),
                ("address", models.TextField()),
                ("is_open_on_sunday", models.BooleanField(default=False)),
                ("is_open_on_monday", models.BooleanField(default=False)),
                ("is_open_on_tuesday", models.BooleanField(default=False)),
                ("is_open_on_wednesday", models.BooleanField(default=False)),
                ("is_open_on_thursday", models.BooleanField(default=False)),
                ("is_open_on_friday", models.BooleanField(default=False)),
                ("is_open_on_saturday", models.BooleanField(default=False)),
                ("email", models.EmailField(max_length=254)),
                ("logo", models.ImageField(upload_to="restaurants")),
                (
                    "restaurant_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restaurants",
                        to="restaurant.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Restaurant",
                "verbose_name_plural": "Restaurants",
            },
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tablenumber", models.IntegerField()),
                ("capacity", models.IntegerField()),
                ("is_occupied", models.BooleanField(default=False)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restaurants",
                        to="restaurant.restaurant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Table",
                "verbose_name_plural": "Table",
            },
        ),
        migrations.CreateModel(
            name="UnitCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the unit category",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "abbreviation",
                    models.CharField(
                        choices=[
                            ("ml", "Milliliters (ml)"),
                            ("g", "Grams (g)"),
                            ("pcs", "Pieces (pcs)"),
                            ("plate", "Plates"),
                            ("cup", "Cups"),
                        ],
                        help_text="Unit abbreviation",
                        max_length=5,
                    ),
                ),
            ],
            options={
                "verbose_name": "Unit Category",
                "verbose_name_plural": "Unit Categories",
            },
        ),
        migrations.CreateModel(
            name="TableQR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "qrlink",
                    models.ImageField(
                        blank=True, null=True, upload_to="table_qrcodes/%Y/%m/%d/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="table",
                        to="restaurant.table",
                    ),
                ),
            ],
            options={
                "verbose_name": "Table QR",
                "verbose_name_plural": "Table QR",
            },
        ),
        migrations.CreateModel(
            name="MenuTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=20)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menutypes",
                        to="restaurant.restaurant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu Types",
                "verbose_name_plural": "Menu Types",
            },
        ),
        migrations.CreateModel(
            name="Menu_Subtype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=20)),
                (
                    "menutype",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menusubtypes",
                        to="restaurant.menutypes",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu Subtype",
                "verbose_name_plural": "Menu Subtypes",
            },
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categorytype",
                    models.CharField(
                        choices=[
                            ("veg", "Veg"),
                            ("non-veg", "Non-Veg"),
                            ("other", "Other"),
                            ("all", "All"),
                        ],
                        default="all",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("video_link", models.URLField()),
                ("item_image", models.ImageField(max_length=200, upload_to="")),
                ("description", models.CharField(max_length=200)),
                ("total_quantity", models.PositiveIntegerField()),
                ("available_quantity", models.PositiveIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "menu_subtype",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_subtypes",
                        to="restaurant.menu_subtype",
                    ),
                ),
                (
                    "menu_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_types",
                        to="restaurant.menutypes",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventories",
                        to="restaurant.restaurant",
                    ),
                ),
                (
                    "unit_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unit_categories",
                        to="restaurant.unitcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory",
                "verbose_name_plural": "Inventories",
            },
        ),
    ]
