# Generated by Django 4.2.7 on 2023-11-07 08:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=500)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('restaurant_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='restaurant.restaurantscategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
