# Generated by Django 4.2.7 on 2023-11-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='table',
            name='qrlink',
            field=models.ImageField(blank=True, null=True, upload_to='table_qrcodes/%Y/%m/%d/'),
        ),
        migrations.DeleteModel(
            name='TableQR',
        ),
    ]
