# Generated by Django 4.2.7 on 2023-11-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_table_is_active_table_qrlink_delete_tableqr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='qrlink',
            field=models.ImageField(blank=True, null=True, upload_to='table_qrcodes'),
        ),
    ]
