# Generated by Django 4.2.7 on 2023-11-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_table_qrlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
