# Generated by Django 4.2.7 on 2023-11-07 10:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_restaurant_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tablenumber', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('is_occupied', models.BooleanField(default=False)),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='restaurant.restaurant')),
            ],
            options={
                'verbose_name': 'Restaurant Table',
                'verbose_name_plural': 'Restaurant Table',
            },
        ),
    ]
