# Generated by Django 4.2.7 on 2023-11-07 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_restauranttable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restauranttable',
            old_name='restaurant_id',
            new_name='restaurant',
        ),
    ]
