# Generated by Django 4.2.7 on 2023-11-20 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_table_tablenumber'),
        ('restaurant', '0005_rename_categorytype_inventory_item_categorytype'),
    ]

    operations = [
    ]
