# Generated by Django 4.2.7 on 2023-11-24 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_merge_20231120_1507'),
        ('restaurant', '0006_merge_20231120_1544'),
    ]

    operations = [
    ]
