# Generated by Django 4.2.7 on 2023-11-07 12:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_tableqr'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the unit category', max_length=20, unique=True)),
                ('abbreviation', models.CharField(choices=[('ml', 'Milliliters (ml)'), ('g', 'Grams (g)'), ('pcs', 'Pieces (pcs)'), ('plate', 'Plates'), ('cup', 'Cups')], help_text='Unit abbreviation', max_length=5)),
            ],
            options={
                'verbose_name': 'Unit Category',
                'verbose_name_plural': 'Unit Categories',
            },
        ),
        migrations.CreateModel(
            name='MenuTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menutypes', to='restaurant.restaurant')),
            ],
            options={
                'verbose_name': 'Menu Types',
                'verbose_name_plural': 'Menu Types',
            },
        ),
        migrations.CreateModel(
            name='Menu_Subtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorytype', models.CharField(choices=[('veg', 'Veg'), ('non-veg', 'Non-Veg')], default=None, max_length=20, null=True)),
                ('name', models.CharField(max_length=20)),
                ('menutype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menusubtypes', to='restaurant.menutypes')),
            ],
            options={
                'verbose_name': 'Menu Subtype',
                'verbose_name_plural': 'Menu Subtypes',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('video_link', models.URLField()),
                ('item_image', models.URLField()),
                ('description', models.CharField(max_length=200)),
                ('total_quantity', models.PositiveIntegerField()),
                ('available_quantity', models.PositiveIntegerField()),
                ('unit_price', models.PositiveIntegerField()),
                ('menu_subtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_subtypes', to='restaurant.menu_subtype')),
                ('menu_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_types', to='restaurant.menutypes')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='restaurant.restaurant')),
                ('unit_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_categories', to='restaurant.unitcategory')),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventories',
            },
        ),
    ]
