# Generated by Django 4.2.7 on 2023-11-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_unitcategory_menutypes_menu_subtype_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_subtype',
            name='categorytype',
            field=models.CharField(choices=[('veg', 'Veg'), ('non-veg', 'Non-Veg'), ('other', 'Other')], default=None, max_length=20, null=True),
        ),
    ]
