# Generated by Django 4.2.7 on 2023-11-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_alter_menu_subtype_categorytype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu_subtype',
            name='categorytype',
        ),
        migrations.AddField(
            model_name='inventory',
            name='categorytype',
            field=models.CharField(choices=[('veg', 'Veg'), ('non-veg', 'Non-Veg'), ('other', 'Other')], default=None, max_length=20, null=True),
        ),
    ]
