# Generated by Django 4.2.7 on 2023-11-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_remove_menu_subtype_categorytype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='categorytype',
        ),
        migrations.AddField(
            model_name='menu_subtype',
            name='categorytype',
            field=models.CharField(choices=[('veg', 'Veg'), ('non-veg', 'Non-Veg')], default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='days_open',
            field=models.ManyToManyField(to='restaurant.day'),
        ),
    ]
