# Generated by Django 4.2.7 on 2023-11-09 05:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_day_remove_inventory_categorytype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='restaurants'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.TextField(),
        ),
    ]
