# Generated by Django 4.2.7 on 2023-11-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_alter_day_options_day_created_at_day_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='days_open',
            field=models.ManyToManyField(blank=True, null=True, to='restaurant.day'),
        ),
    ]
