# Generated by Django 4.2.7 on 2023-11-09 09:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_alter_restaurant_days_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='days_open',
        ),
        migrations.AddField(
            model_name='day',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_open_on_friday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_open_on_monday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_open_on_saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_open_on_sunday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_open_on_thursday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_open_on_tuesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_open_on_wednesday',
            field=models.BooleanField(default=False),
        ),
    ]
