# Generated by Django 4.2.7 on 2023-11-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_delete_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu_subtype',
            name='categorytype',
        ),
        migrations.AddField(
            model_name='inventory',
            name='categorytype',
            field=models.CharField(choices=[('veg', 'Veg'), ('non-veg', 'Non-Veg'), ('other', 'Other')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='item_image',
            field=models.ImageField(max_length=200, upload_to=''),
        ),
    ]
