# Generated by Django 4.2.7 on 2023-11-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_delete_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='item_image',
            field=models.ImageField(max_length=200, upload_to=''),
        ),
    ]
