# Generated by Django 4.2.7 on 2023-11-09 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0017_alter_inventory_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu_subtype',
            name='categorytype',
        ),
    ]
