# Generated by Django 4.2.7 on 2023-11-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0017_remove_menu_subtype_categorytype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
